"""init

Revision ID: 12d0f52a6567
Revises: 
Create Date: 2018-10-22 21:20:49.171140

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '12d0f52a6567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulcrum_form',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulcrum_project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulcrum_field',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('data_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('TextField', 'YesNoField', 'Label', 'Section', 'ChoiceField', 'ClassificationField', 'PhotoField', 'VideoField', 'AudioField', 'BarcodeField', 'DateTimeField', 'TimeField', 'Repeatable', 'AddressField', 'SignatureField', 'HyperlinkField', 'CalculatedField', 'RecordLinkField', name='field_types'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulcrum_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Numeric(), nullable=True),
    sa.Column('course', sa.Numeric(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fulcrum_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulcrum_media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('track', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('media_type', sa.Enum('photo', 'audio', 'video', name='media_types'), nullable=False),
    sa.Column('storage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fulcrum_field.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['fulcrum_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulcrum_value',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TextField', 'YesNoField', 'Label', 'Section', 'ChoiceField', 'ClassificationField', 'PhotoField', 'VideoField', 'AudioField', 'BarcodeField', 'DateTimeField', 'TimeField', 'Repeatable', 'AddressField', 'SignatureField', 'HyperlinkField', 'CalculatedField', 'RecordLinkField', name='field_types'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fulcrum_field.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['fulcrum_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('fulcrum_value')
    op.drop_table('fulcrum_media')
    op.drop_table('fulcrum_record')
    op.drop_table('fulcrum_field')
    op.drop_table('fulcrum_project')
    op.drop_table('fulcrum_form')
    # ### end Alembic commands ###
