"""removed_attr

Revision ID: dd3a80e88513
Revises: 8a5ad99f2691
Create Date: 2018-10-26 14:13:56.314605

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'dd3a80e88513'
down_revision = '8a5ad99f2691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulcrum_field', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_field_removed'), 'fulcrum_field', ['removed'], unique=False)
    op.add_column('fulcrum_form', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_form_removed'), 'fulcrum_form', ['removed'], unique=False)
    op.add_column('fulcrum_media', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_media_removed'), 'fulcrum_media', ['removed'], unique=False)
    op.drop_index('idx_fulcrum_media_point', table_name='fulcrum_media')
    op.drop_index('idx_fulcrum_media_track', table_name='fulcrum_media')
    op.add_column('fulcrum_project', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_project_removed'), 'fulcrum_project', ['removed'], unique=False)
    op.add_column('fulcrum_record', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_record_removed'), 'fulcrum_record', ['removed'], unique=False)
    op.drop_index('idx_fulcrum_record_point', table_name='fulcrum_record')
    op.add_column('fulcrum_value', sa.Column('removed', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.create_index(op.f('ix_fulcrum_value_removed'), 'fulcrum_value', ['removed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulcrum_value_removed'), table_name='fulcrum_value')
    op.drop_column('fulcrum_value', 'removed')
    op.create_index('idx_fulcrum_record_point', 'fulcrum_record', ['point'], unique=False)
    op.drop_index(op.f('ix_fulcrum_record_removed'), table_name='fulcrum_record')
    op.drop_column('fulcrum_record', 'removed')
    op.drop_index(op.f('ix_fulcrum_project_removed'), table_name='fulcrum_project')
    op.drop_column('fulcrum_project', 'removed')
    op.create_index('idx_fulcrum_media_track', 'fulcrum_media', ['track'], unique=False)
    op.create_index('idx_fulcrum_media_point', 'fulcrum_media', ['point'], unique=False)
    op.drop_index(op.f('ix_fulcrum_media_removed'), table_name='fulcrum_media')
    op.drop_column('fulcrum_media', 'removed')
    op.drop_index(op.f('ix_fulcrum_form_removed'), table_name='fulcrum_form')
    op.drop_column('fulcrum_form', 'removed')
    op.drop_index(op.f('ix_fulcrum_field_removed'), table_name='fulcrum_field')
    op.drop_column('fulcrum_field', 'removed')
    # ### end Alembic commands ###
