"""initial

Revision ID: f9d4f64f6cef
Revises: 
Create Date: 2018-10-23 18:56:49.012824

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f9d4f64f6cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulcrum_form',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_form_name'), 'fulcrum_form', ['name'], unique=False)
    op.create_table('fulcrum_project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_project_name'), 'fulcrum_project', ['name'], unique=False)
    op.create_table('fulcrum_field',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('data_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('TextField', 'YesNoField', 'Label', 'Section', 'ChoiceField', 'ClassificationField', 'PhotoField', 'VideoField', 'AudioField', 'BarcodeField', 'DateTimeField', 'TimeField', 'Repeatable', 'AddressField', 'SignatureField', 'HyperlinkField', 'CalculatedField', 'RecordLinkField', name='field_types'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_field_data_name'), 'fulcrum_field', ['data_name'], unique=False)
    op.create_index(op.f('ix_fulcrum_field_label'), 'fulcrum_field', ['label'], unique=False)
    op.create_table('fulcrum_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Numeric(), nullable=True),
    sa.Column('course', sa.Numeric(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fulcrum_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_record_point'), 'fulcrum_record', ['point'], unique=False)
    op.create_index(op.f('ix_fulcrum_record_status'), 'fulcrum_record', ['status'], unique=False)
    op.create_table('fulcrum_media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('track', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.Column('media_type', sa.Enum('photo', 'audio', 'video', name='media_types'), nullable=False),
    sa.Column('storage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fulcrum_field.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['fulcrum_form.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['fulcrum_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_media_media_type'), 'fulcrum_media', ['media_type'], unique=False)
    op.create_table('fulcrum_value',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('type', sa.Enum('TextField', 'YesNoField', 'Label', 'Section', 'ChoiceField', 'ClassificationField', 'PhotoField', 'VideoField', 'AudioField', 'BarcodeField', 'DateTimeField', 'TimeField', 'Repeatable', 'AddressField', 'SignatureField', 'HyperlinkField', 'CalculatedField', 'RecordLinkField', name='field_types'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fulcrum_field.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['fulcrum_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulcrum_value_type'), 'fulcrum_value', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fulcrum_value_type'), table_name='fulcrum_value')
    op.drop_table('fulcrum_value')
    op.drop_index(op.f('ix_fulcrum_media_media_type'), table_name='fulcrum_media')
    op.drop_table('fulcrum_media')
    op.drop_index(op.f('ix_fulcrum_record_status'), table_name='fulcrum_record')
    op.drop_index(op.f('ix_fulcrum_record_point'), table_name='fulcrum_record')
    op.drop_table('fulcrum_record')
    op.drop_index(op.f('ix_fulcrum_field_label'), table_name='fulcrum_field')
    op.drop_index(op.f('ix_fulcrum_field_data_name'), table_name='fulcrum_field')
    op.drop_table('fulcrum_field')
    op.drop_index(op.f('ix_fulcrum_project_name'), table_name='fulcrum_project')
    op.drop_table('fulcrum_project')
    op.drop_index(op.f('ix_fulcrum_form_name'), table_name='fulcrum_form')
    op.drop_table('fulcrum_form')
    # ### end Alembic commands ###
